version: '3.7'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.22
    container_name: elasticsearch
    environment:
      - discovery.type=${DISCOVERY_TYPE}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - xpack.security.enabled=${XPACK_SECURITY_ENABLED}
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - esplugins:/usr/share/elasticsearch/plugins
    mem_limit: 1g
    privileged: true

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.22
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=${ELASTICSEARCH_HOSTS}
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME}
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    volumes:
      - kibdata:/usr/share/kibana
    privileged: true

volumes:
  esdata:
    driver: local
    driver_opts:
      type: none
      device: /var/lib/docker/elasticsearch_data
      o: bind

  esplugins:
    driver: local
    driver_opts:
      type: none
      device: /var/lib/docker/elasticsearch_plugins
      o: bind

  kibdata:
    driver: local
    driver_opts:
      type: none
      device: /var/lib/docker/kibana_data
      o: bind

